# Generated by Django 5.2.14 on 2026-05-15 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_service', models.CharField(max_length=512)),
                ('audience', models.CharField(max_length=512)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('playful', 'Playful'), ('stylish', 'Stylish'), ('bold', 'Bold')], default='friendly', max_length=32)),
                ('platform', models.CharField(choices=[('meta', 'Meta'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], default='meta', max_length=32)),
                ('key_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('cta', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='studio.adbrief')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('audience', models.CharField(blank=True, default='', max_length=512)),
                ('tone', models.CharField(blank=True, default='', max_length=128)),
                ('colors', models.CharField(blank=True, default='#8b5cf6', max_length=32)),
                ('goal', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/%Y/%m/')),
                ('file_url', models.URLField(blank=True, default='', max_length=1024)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copy', models.TextField()),
                ('social_posts', models.JSONField(default=list)),
                ('pdf_brochure_url', models.URLField(blank=True, default='', max_length=1024)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='brochures/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_creatives', to='studio.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
